global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'geofence-api'
    static_configs:
      - targets: ['api:3001']
    metrics_path: '/health'
    scrape_interval: 30s

  - job_name: 'geofence-dashboard'
    static_configs:
      - targets: ['dashboard:3002']
    metrics_path: '/'
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 60s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 60s

  - job_name: 'mqtt-broker'
    static_configs:
      - targets: ['mqtt-broker:1883']
    scrape_interval: 60s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 60s